#' Regress out Nuisance Parameters in Time Series
#'
#' Regress out BOLD data Nuisance Parameters, the Parameters are identified in
#' rsBOLDCollectNuisParams().
#'
#' @param boldMat BOLD time series matrix
#' @param mocoParam MOCO registration parameters
#' @param NuisList BOLD Nuisance Parameter list generated by rsBOLDCollectNuisParams()
#' @param goodtimes list of interger index of good timepoints
#' @param providePlot Boolean determine whether descriptive statistics should be provided
#' if TRUE, the plot will be cached and can be called
#'
#' @return BOLD time series matrix after regression
#'
#'
#'
#' @export regressNuisParams



regressNuisParams <- function(
  boldMat, mocoParam, NuisList, goodtimes, providePlot = TRUE){
  #check requirements
  if (!usePkg("ANTsR")) {
    print("Need ANTsR package")
    return(NULL)
  }


  if (!usePkg("R.cache")) {
    print("Need R.cache package")
    return(NULL)
  }

  if(!usePkg("pracma")){
    print("Need pracma package")
    return(NULL)
  }

  if (providePlot){
    if (!usePkg("ggplot2")) {
      print("Need ggplot2 package")
      return(NULL)
    }
  }


  #convert inputs
  reg_params <- as.matrix(mocoParam[,3:8])
  ctxVox <- NuisList$ctxVox
  ctxMean <- NuisList$ctxMean
  tissueNuis <- NuisList$tissueNuis
  tissueDeriv <- NuisList$tissueDeriv
  compcorNuis <- NuisList$compcorNuis

  #moco detrend
  moco = cbind(reg_params, reg_params*reg_params)
  moco = detrend(moco)
  mocoDeriv = rbind( rep(0,dim(moco)[2]), diff(moco,1) )

  #Nuisance Parameters
  nuissance = cbind( moco, mocoDeriv, tissueNuis, tissueDeriv, compcorNuis )

  #Regress out Nuisance signals
  boldMat[goodtimes,] <- residuals( lm( boldMat[goodtimes,] ~ nuissance[goodtimes,] ) )

  #plot
  if(providePlot){
    #required plot inputs
    nTimes <- dim(reg_params)[1]
    ctxVox <- NuisList$ctxVox
    ctxMean <- NuisList$ctxMean
    ctxMeanRegressed = rowMeans(boldMat[,ctxVox])

    cortex.dat =  data.frame( Time=rep(1:nTimes,2) )
    cortex.dat$Values = c(ctxMean, ctxMeanRegressed)
    cortex.dat$Type = c(rep("Original",nTimes), rep("Regressed",nTimes))
    cortexPlot = ggplot(cortex.dat, aes(x=Time, y=Values, group=Type, colour=Type))
    cortexPlot = cortexPlot + geom_line(size=0.5)
    cortexPlot = cortexPlot + theme(text=element_text(size=10), legend.position="top")
    cortexPlot = cortexPlot + ggtitle("Effect of nuisance parameter regression")
    cortexPlot = cortexPlot + facet_grid(Type ~ ., scales="free" )

    saveCache(cortexPlot,key = list("cp"))
  }
  return(boldMat)
}
